name: Publish docs
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Pytest
    types:
      - completed
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/mkdocs.yml'
      - 'mkdocs.yml'
jobs:
  mkdocs:
    name: Publish docs
    runs-on: ubuntu-latest
    if: github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: dawidd6/action-download-artifact@v5
        with:
          workflow: tests-pytest.yml
          branch: main
          event: push
          name: coverage-report
          path: docs/tests/coverage

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          REQUIREMENTS: docs/requirements.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
